### ISSUE TITLE
No longer seems to work with Cody v1.46.0

### ISSUE THREAD

**Issue by vadi2** [mnismt/codyplusplus#11]
Add folder to Cody doesn't seem to add the folder anymore as of Cody v1.46.0.

**Comment by mnismt** [comment]
Hi @vadi2, I just tested it and everything works fine. Please check it again, as it might be a bit laggy for large folders (which could be the reason it's not working properly I guess)

https://github.com/user-attachments/assets/64d2a39d-9d4f-44b7-ac44-f2afd99951d3

**Comment by vadi2** [comment]
Hmm, using this on Linux, I had to actually select the folder first, then right-click to bring up the menu, and then add the files to the context.

Just right-clicking on the folder, without selecting it first using a left-click, wasn't working as expected.
